function start() {
  $(bg).attr("src", "BG1.png")
  $(play).remove()
  let barkboard = 0
  $(overScreen).append("<div id = bark><p id = barkP>Right, class. Today we're learning about the carbon cycle, not a bike made out of coal, Tom.</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
  let a = setInterval(function() {$(barkAn).attr("src", `BarkWhiteboard${barkboard % 8}.png`); barkboard ++}, 125)
  $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
  $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
  $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
  setTimeout(function() {
    clearInterval(a)
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>Oh, thank goodness! I thought we had to pedal the atmosphere.</p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "261px")
    $(tom).css("margin-top", "-366px")
  }, 5000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>Carbon is EVERYWHERE. In the air, in plants, in animals and in your brain if you have one.</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "20px")
    $(tom).css("margin-top", "-193px")
  }, 10000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP>My brain runs on pizza, not carbon, thank you.</p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "261px")
    $(mot).css("margin-top", "220px")
  }, 15000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>When plants photosynthesise, they suck carbon dioxide from the air and make sugar-</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "54px")
    $(mot).css("margin-top", "358px")
  }, 20000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP>Wait, so plants basically fart sugar?</p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "261px")
    $(edward).css("margin-top", "-297px")
  }, 25000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>NO! They produce glucose, not fart-glucose.</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "123px")
    $(edward).css("margin-top", "-193px")
  }, 30000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>Then, animals eat the plants and other animals eat those and, well, the carbon goes on a road trip.</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "20px")
  }, 35000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>ROAD TRIP! Does it have a playlist?</p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "261px")
    $(tom).css("margin-top", "-297px")
  }, 40000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>Yes, it's called \"Breathe In, Breath Out: The Respiration Mix.\"</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "88px")
    $(tom).css("margin-top", "-193px")
  }, 45000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>When living things die, carbon goes back to the ground until it becomes fossil fuels after millions of years.</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "-50px")
  }, 50000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>So that means that dinosaurs are basically... gasoline?</p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "261px")
    $(tom).css("margin-top", "-332px")
  }, 55000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>Correct. You are fuelling your dad's car with a prehistoric chicken.</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "88px")
    $(tom).css("margin-top", "-193px")
  }, 60000)
  setTimeout(function() {
    $(bg).attr("src", "BG2.png")
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotStand.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP>Guys, the carbon cycle is totally rigged! We're releasing too much carbon dioxide by burning ancient lizards!</p><br><img id = edwardAn src = edwardStand.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomStand.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-600px", "margin-left")
    $(tom).css("margin-top", "-200px", "margin-left")
  }, 65000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP>And it's causing climate chaos - like floods, fires and ice melting where penguins live.</p><br><img id = motAn src = MotStand.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardStand.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomStand.png></div>")
    $(mot).css("margin-top", "300px")
    $(edward).css("margin-top", "-300px")
  }, 70000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotStand.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardStand.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>THIS IS A CRIME AGAINST SNOWMEN!</p><br><img id = tomAn src = TomStand.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-300px")
    $(tom).css("margin-top", "-350px")
  }, 75000)
  setTimeout(function() {
    $(bg).attr("src", "BG3.png")
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSign.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP>We must act. For the trees, For the polar bears. For... the pizza.</p><br><img id = edwardAn src = edwardSign.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSign.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-500px")
    $(tom).css("margin-top", "-200px")
  }, 80000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP>I'm going to recycle EVERYTHING. Even my homework!</p><br><img id = motAn src = MotSign.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardSign.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSign.png></div>")
    $(mot).css("margin-top", "300px")
    $(edward).css("margin-top", "-300px")
  }, 85000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSign.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardSign.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>I'll only eat meat on days ending in Z. That's none of them!</p><br><img id = tomAn src = TomSign.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-300px")
    $(tom).css("margin-top", "-350px")
  }, 90000)
  setTimeout(function() {
    $(bg).attr("src", "BG4.png")
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotStand.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardBin.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>Look! Metal! We can recycle this instead of digging more holes into the Earth!</p><br><img id = tomAn src = TomMetal.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-300px")
    $(tom).css("margin-top", "-450px")
  }, 95000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP>Every can counts! Every spoon matters! Every rusted old shopping trolley is a piece of Earth's soul!</p><br><img id = motAn src = MotDrama.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardBin.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomMetal.png></div>")
    $(mot).css("margin-top", "200px", "margin-left", "-415px")
    $(edward).css("margin-top", "-300px")
  }, 100000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotStand.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP>Let's smelt responsibly.</p><br><img id = edwardAn src = edwardBin.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomMetal.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-400px")
    $(tom).css("margin-top", "-200px")
  }, 105000)
  setTimeout(function() {
    $(bg).attr("src", "BG3.png")
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotAct.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP>I'm a volcano! I release carbon slowly, unlike you lot!</p><br><img id = edwardAn src = edwardAct.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomAct.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-500px")
    $(tom).css("margin-top", "-200px")
  }, 110000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP>BEHOLD! We are the Carbon Crusaders!</p><br><img id = motAn src = MotAct.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardAct.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomAct.png></div>")
    $(mot).css("margin-top", "300px")
    $(edward).css("margin-top", "-200px")
  }, 115000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotAct.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = edwardAct.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>And we say: Cut the carbon! Save the penguins! Hug a tree today!</p><br><img id = tomAn src = TomAct.png></div>")
    $(mot).css("margin-top", "500px")
    $(edward).css("margin-top", "-300px")
    $(tom).css("margin-top", "-350px")
  }, 120000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = tv><p id = tvP>In breaking news, three local students have sparked a recycling revolution.</p><br><img id = tvAn src = TV.png></div>")
  }, 125000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = tv><p id = tvP>Metal bins are emptying. Solar panels are selling out. Trees are being hugged across the nation.</p><br><img id = tvAn src = TV.png></div>")
    $(tv).css("margin-top", "65px")
  }, 130000)
  setTimeout(function() {
    $(bg).attr("src", "BG1.png")
    $(overScreen).text("")
    barkboard = 0
    $(overScreen).append("<div id = bark><p id = barkP>So, who can tell me what we've learnt?</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    a = setInterval(function() {$(barkAn).attr("src", `BarkWhiteboard${barkboard % 8}.png`); barkboard ++}, 125)
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "160px")
  }, 135000)
  setTimeout(function() {
    clearInterval(a)
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP>Carbon belongs everywhere, but not all at once.</p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "263px")
    $(tom).css("margin-top", "-297px")
  }, 140000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP>Recycling metal reduces mining.</p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "263px")
    $(mot).css("margin-top", "289px")
    $(tom).css("margin-top", "-193px")
  }, 145000)
  setTimeout(function() {
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP></p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP>Too much carbon dioxide causes global warming which causes polar bears to be grumpy.</p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "263px")
    $(mot).css("margin-top", "358px")
    $(edward).css("margin-top", "-435px")
  }, 150000)
  setTimeout(function() {
    $(bg).attr("src", "BG1.png")
    $(overScreen).text("")
    $(overScreen).append("<div id = bark><p id = barkP>Looks like you three finally absorbed something.</p><br><img id = barkAn src = BarkWhiteboard0.png></div>")
    $(overScreen).append("<div id = mot><p id = motP></p><br><img id = motAn src = MotSit.png></div>")
    $(overScreen).append("<div id = edward><p id = edwardP></p><br><img id = edwardAn src = EdwardSit.png></div>")
    $(overScreen).append("<div id = tom><p id = tomP></p><br><img id = tomAn src = TomSit.png></div>")
    $(bark).css("margin-top", "125px")
  }, 155000)
}
$(play).click(function() {$(this).attr("src", "PlayP.png"); setTimeout(function() {start()}, 500)})